name: Build 

on:
  push:
    branches: ['main']
    
jobs: 
  build: 
      runs-on: ubuntu-20.04
      steps: 
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 18.x
          cache: npm
      - name: Install dependencies 
        run: npm install 
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          publish_branch: gh-pages
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
